name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      # Node を先にセットアップ（pnpm キャッシュも有効化）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # package.json の packageManager を尊重して pnpm を用意（versionは固定しない）
      - name: Setup pnpm (respect packageManager)
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      # ★ 依存をここで入れる（ここより前に lint 等を回さない）
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          HUSKY: 0 # CI では husky の postinstall を無効化（使ってなければ不要）

      # ネイティブモジュール対策（better-sqlite3 を使っていなければそのままでもOK）
      - name: Rebuild native deps (optional)
        run: pnpm rebuild better-sqlite3 || true

      - name: Run linter
        run: pnpm run lint

      - name: Type check
        run: pnpm run typecheck --if-present

      - name: Run tests
        run: pnpm run test --if-present

      - name: Build
        run: pnpm run build
