name: ci
on:
  push:
  pull_request:
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NUXT_PUBLIC_SITE_URL: https://kotorilab.jp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup pnpm (respect packageManager)
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Type check
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test -- --run
      # optional:
      - name: Build
        run: pnpm build
      - name: API tests
        run: pnpm run test:api
      - name: Check sitemap/robots host
        run: pnpm run check:meta
      - name: Smoke OGP endpoint
        env:
          NUXT_PUBLIC_SITE_URL: https://kotorilab.jp
        run: pnpm run smoke:og
      - name: Smoke OG (GET with retry)
        run: SMOKE_URL=https://kotorilab.jp pnpm run smoke:og
