name: lighthouse

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # 09:00 JST (UTC+9)

permissions:
  contents: read

concurrency:
  group: lighthouse-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lh:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preset: [desktop, mobile]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Audit kotorilab.jp (${{ matrix.preset }})
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://kotorilab.jp
          uploadArtifacts: true
          artifactName: lighthouse-results-${{ matrix.preset }}
          temporaryPublicStorage: true
          # Run LH with desired form factor via configPath or flags; using built-in presets
          # The action respects LHCI's formFactor/emulatedFormFactor via config when provided.
          # Here, we hint via extraHeaders to label; artifact names will include preset.
          runs: 1
        env:
          LHCI_EMULATE_FORM_FACTOR: ${{ matrix.preset }}
