name: lighthouse

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # 09:00 JST (UTC+9)

permissions:
  contents: read

concurrency:
  group: lighthouse-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lh:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preset: [desktop, mobile]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Warm up homepage
        if: ${{ matrix.preset == 'desktop' }}
        continue-on-error: true
        run: |
          set -Eeuo pipefail
          base="${SITE_ORIGIN:-https://migakiexplorer.jp}"
          ua="gh-actions-warmup"
          # 候補URL（軽い順）。1つでも成功したら成功扱い。
          candidates=(
            "$base/api/health"
            "$base/"
          )
          try() { curl -fsSIL --max-time 20 --connect-timeout 10 -A "$ua" "$1" -w " HTTP %{http_code}\n" ; }
          for attempt in 1 2 3 4 5; do
            for u in "${candidates[@]}"; do
              echo "Attempt $attempt: default -> $u"
              if try "$u"; then exit 0; fi
              echo "Attempt $attempt: force IPv4 + TLS1.2 -> $u"
              if curl -fsSIL -4 --tlsv1.2 --max-time 20 --connect-timeout 10 -A "$ua" "$u" -w " HTTP %{http_code}\n" ; then
                exit 0
              fi
            done
            sleep $((attempt*2))
          done
          echo "::warning::Warm-up failed after retries; continuing to Lighthouse"

      - name: Audit migakiexplorer.jp (desktop)
        if: ${{ matrix.preset == 'desktop' }}
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://migakiexplorer.jp
          configPath: .lighthouserc.desktop.json
          uploadArtifacts: true
          artifactName: lighthouse-results-desktop
          temporaryPublicStorage: true
          runs: 3

      - name: Warm up homepage
        if: ${{ matrix.preset == 'mobile' }}
        continue-on-error: true
        run: |
          set -Eeuo pipefail
          base="${SITE_ORIGIN:-https://migakiexplorer.jp}"
          ua="gh-actions-warmup"
          # 候補URL（軽い順）。1つでも成功したら成功扱い。
          candidates=(
            "$base/api/health"
            "$base/"
          )
          try() { curl -fsSIL --max-time 20 --connect-timeout 10 -A "$ua" "$1" -w " HTTP %{http_code}\n" ; }
          for attempt in 1 2 3 4 5; do
            for u in "${candidates[@]}"; do
              echo "Attempt $attempt: default -> $u"
              if try "$u"; then exit 0; fi
              echo "Attempt $attempt: force IPv4 + TLS1.2 -> $u"
              if curl -fsSIL -4 --tlsv1.2 --max-time 20 --connect-timeout 10 -A "$ua" "$u" -w " HTTP %{http_code}\n" ; then
                exit 0
              fi
            done
            sleep $((attempt*2))
          done
          echo "::warning::Warm-up failed after retries; continuing to Lighthouse"

      - name: Audit migakiexplorer.jp (mobile)
        if: ${{ matrix.preset == 'mobile' }}
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://migakiexplorer.jp
          configPath: .lighthouserc.mobile.json
          uploadArtifacts: true
          artifactName: lighthouse-results-mobile
          temporaryPublicStorage: true
          runs: 3
        env:
          LHCI_EMULATE_FORM_FACTOR: mobile
