name: lighthouse

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # 09:00 JST (UTC+9)

permissions:
  contents: read

concurrency:
  group: lighthouse-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lh:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preset: [desktop, mobile]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Warm up homepage
        if: ${{ matrix.preset == 'desktop' }}
        run: |
          curl -sS https://kotorilab.jp/ -o /dev/null -w "HTTP %{http_code}\n"
          sleep 2

      - name: Audit kotorilab.jp (desktop)
        if: ${{ matrix.preset == 'desktop' }}
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://kotorilab.jp
          configPath: .lighthouserc.desktop.json
          uploadArtifacts: true
          artifactName: lighthouse-results-desktop
          temporaryPublicStorage: true
          runs: 3

      - name: Warm up homepage
        if: ${{ matrix.preset == 'mobile' }}
        run: |
          curl -sS https://kotorilab.jp/ -o /dev/null -w "HTTP %{http_code}\n"
          sleep 2

      - name: Audit kotorilab.jp (mobile)
        if: ${{ matrix.preset == 'mobile' }}
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://kotorilab.jp
          configPath: .lighthouserc.mobile.json
          uploadArtifacts: true
          artifactName: lighthouse-results-mobile
          temporaryPublicStorage: true
          runs: 3
        env:
          LHCI_EMULATE_FORM_FACTOR: mobile
