name: lighthouse

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # 09:00 JST (UTC+9)

permissions:
  contents: read

concurrency:
  group: lighthouse-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lh:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preset: [desktop, mobile]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Warm up homepage
        if: ${{ matrix.preset == 'desktop' }}
        run: |
          set -Eeuo pipefail
          url="https://migakiexplorer.jp/"
          ua="gh-actions-warmup"
          attempt=0
          while [ $attempt -lt 3 ]; do
            attempt=$((attempt+1))
            echo "Attempt ${attempt}: default curl"
            if curl -sS -A "$ua" "$url" -o /dev/null -w "HTTP %{http_code}\n"; then
              exit 0
            fi
            echo "Attempt ${attempt}: force IPv4 + TLS1.2"
            if curl -sS -4 --tlsv1.2 -A "$ua" "$url" -o /dev/null -w "HTTP %{http_code}\n"; then
              exit 0
            fi
            sleep $((attempt*3))
          done
          echo "Warm-up failed after retries" >&2
          exit 1

      - name: Audit migakiexplorer.jp (desktop)
        if: ${{ matrix.preset == 'desktop' }}
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://migakiexplorer.jp
          configPath: .lighthouserc.desktop.json
          uploadArtifacts: true
          artifactName: lighthouse-results-desktop
          temporaryPublicStorage: true
          runs: 3

      - name: Warm up homepage
        if: ${{ matrix.preset == 'mobile' }}
        run: |
          set -Eeuo pipefail
          url="https://migakiexplorer.jp/"
          ua="gh-actions-warmup"
          attempt=0
          while [ $attempt -lt 3 ]; do
            attempt=$((attempt+1))
            echo "Attempt ${attempt}: default curl"
            if curl -sS -A "$ua" "$url" -o /dev/null -w "HTTP %{http_code}\n"; then
              exit 0
            fi
            echo "Attempt ${attempt}: force IPv4 + TLS1.2"
            if curl -sS -4 --tlsv1.2 -A "$ua" "$url" -o /dev/null -w "HTTP %{http_code}\n"; then
              exit 0
            fi
            sleep $((attempt*3))
          done
          echo "Warm-up failed after retries" >&2
          exit 1

      - name: Audit migakiexplorer.jp (mobile)
        if: ${{ matrix.preset == 'mobile' }}
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://migakiexplorer.jp
          configPath: .lighthouserc.mobile.json
          uploadArtifacts: true
          artifactName: lighthouse-results-mobile
          temporaryPublicStorage: true
          runs: 3
        env:
          LHCI_EMULATE_FORM_FACTOR: mobile
